# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\josep\Documents\DevelopPython\Sistema_de_ventas\ui\FrmIngreso.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(999, 769)
        MainWindow.setStyleSheet("/* Estilos comunes para varios controles */\n"
"QWidget {\n"
"    background-color: #deede3;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 961, 691))
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"    background-color: #deede3;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px;\n"
"}\n"
"\n"
"QTabWidget::tab {\n"
"    background-color: #deede3;\n"
"    border: 1px solid #1e362d;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QTabWidget::tab:selected {\n"
"    background-color: #c0dacb;\n"
"    border: 1px solid #1e362d;\n"
"    border-bottom: 1px solid #c0dacb;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    background-color: #deede3;\n"
"    border: 1px solid #1e362d;\n"
"    border-top: none;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 921, 631))
        self.groupBox_3.setStyleSheet("/* Estilos para QGroupBox */\n"
"QGroupBox {\n"
"    border: 2px solid #1e362d;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    color: #1e362d;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    left: 10px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: none;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(25, 30, 73, 27))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.txtBuscar = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtBuscar.setGeometry(QtCore.QRect(100, 20, 120, 35))
        self.txtBuscar.setStyleSheet("QLineEdit {\n"
"    background-color: #deede3;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtBuscar.setObjectName("txtBuscar")
        self.btnBuscar = QtWidgets.QPushButton(self.groupBox_3)
        self.btnBuscar.setGeometry(QtCore.QRect(235, 20, 85, 37))
        self.btnBuscar.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c0dacb, stop: 1 #96bfab);\n"
"    color: #ffffff;\n"
"    border: 1px solid #1e362d;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #689f84, stop: 1 #96bfaa);\n"
"    border: 1px solid #96bfaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #2a5242, stop: 1 #32624d);\n"
"    border: 1px solid #32624d;\n"
"}")
        self.btnBuscar.setObjectName("btnBuscar")
        self.btnAnular = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAnular.setGeometry(QtCore.QRect(330, 20, 85, 37))
        self.btnAnular.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c0dacb, stop: 1 #96bfab);\n"
"    color: #ffffff;\n"
"    border: 1px solid #1e362d;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #689f84, stop: 1 #96bfaa);\n"
"    border: 1px solid #96bfaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #2a5242, stop: 1 #32624d);\n"
"    border: 1px solid #32624d;\n"
"}")
        self.btnAnular.setObjectName("btnAnular")
        self.btnImprimir = QtWidgets.QPushButton(self.groupBox_3)
        self.btnImprimir.setGeometry(QtCore.QRect(425, 20, 85, 37))
        self.btnImprimir.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c0dacb, stop: 1 #96bfab);\n"
"    color: #ffffff;\n"
"    border: 1px solid #1e362d;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #689f84, stop: 1 #96bfaa);\n"
"    border: 1px solid #96bfaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #2a5242, stop: 1 #32624d);\n"
"    border: 1px solid #32624d;\n"
"}")
        self.btnImprimir.setObjectName("btnImprimir")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(25, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(160, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(295, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_26.setObjectName("label_26")
        self.txtFechaInicio = QtWidgets.QDateEdit(self.groupBox_3)
        self.txtFechaInicio.setGeometry(QtCore.QRect(20, 100, 110, 30))
        self.txtFechaInicio.setAcceptDrops(False)
        self.txtFechaInicio.setStyleSheet("/* Estilos para QDateEdit */\n"
"QDateEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QDateEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}")
        self.txtFechaInicio.setAlignment(QtCore.Qt.AlignCenter)
        self.txtFechaInicio.setCalendarPopup(True)
        self.txtFechaInicio.setObjectName("txtFechaInicio")
        self.txtFechaFin = QtWidgets.QDateEdit(self.groupBox_3)
        self.txtFechaFin.setGeometry(QtCore.QRect(145, 100, 110, 30))
        self.txtFechaFin.setStyleSheet("/* Estilos para QDateEdit */\n"
"QDateEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QDateEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}")
        self.txtFechaFin.setAlignment(QtCore.Qt.AlignCenter)
        self.txtFechaFin.setCalendarPopup(True)
        self.txtFechaFin.setObjectName("txtFechaFin")
        self.cmbEstado = QtWidgets.QComboBox(self.groupBox_3)
        self.cmbEstado.setGeometry(QtCore.QRect(270, 100, 110, 30))
        self.cmbEstado.setStyleSheet("QComboBox {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QComboBox::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.cmbEstado.setObjectName("cmbEstado")
        self.cmbEstado.addItem("")
        self.cmbEstado.addItem("")
        self.tbIngreso = QtWidgets.QTableView(self.groupBox_3)
        self.tbIngreso.setGeometry(QtCore.QRect(20, 150, 871, 451))
        self.tbIngreso.setStyleSheet("QTableView {\n"
"    background-color: #f2f7f4;\n"
"    border: 1px solid #cccccc;\n"
"    selection-background-color: #96bfaa;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QTableView QHeaderView {\n"
"    background-color: #c0dacb;\n"
"    color: #333333;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableView QHeaderView::section {\n"
"    background-color: #deede3;\n"
"    color: #333333;\n"
"    padding: 6px;\n"
"    border: 1px solid #1e362d;\n"
"}\n"
"\n"
"QTableView QHeaderView::section:checked {\n"
"    background-color: #96bfaa;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #96bfaa;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QTableView::item:focus {\n"
"    background-color: #96bfaa;\n"
"    color: #ffffff;\n"
"    outline: none;\n"
"}")
        self.tbIngreso.setObjectName("tbIngreso")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 931, 631))
        self.groupBox.setStyleSheet("/* Estilos para QGroupBox */\n"
"QGroupBox {\n"
"    border: 2px solid #1e362d;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    color: #1e362d;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    left: 10px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: none;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 55, 21))
        self.label_3.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.btnRegistrar = QtWidgets.QPushButton(self.groupBox)
        self.btnRegistrar.setGeometry(QtCore.QRect(820, 110, 85, 37))
        self.btnRegistrar.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c0dacb, stop: 1 #96bfab);\n"
"    color: #ffffff;\n"
"    border: 1px solid #1e362d;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #689f84, stop: 1 #96bfaa);\n"
"    border: 1px solid #96bfaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #2a5242, stop: 1 #32624d);\n"
"    border: 1px solid #32624d;\n"
"}")
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.txtCodigo = QtWidgets.QLineEdit(self.groupBox)
        self.txtCodigo.setGeometry(QtCore.QRect(135, 60, 120, 35))
        self.txtCodigo.setStyleSheet("QLineEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtCodigo.setReadOnly(True)
        self.txtCodigo.setObjectName("txtCodigo")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 111, 21))
        self.label_6.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.txtFecha = QtWidgets.QDateEdit(self.groupBox)
        self.txtFecha.setGeometry(QtCore.QRect(670, 60, 120, 35))
        self.txtFecha.setAcceptDrops(False)
        self.txtFecha.setStyleSheet("/* Estilos para QDateEdit */\n"
"QDateEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QDateEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}")
        self.txtFecha.setAlignment(QtCore.Qt.AlignCenter)
        self.txtFecha.setCalendarPopup(True)
        self.txtFecha.setObjectName("txtFecha")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(285, 70, 91, 21))
        self.label_12.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.cmbComprobante = QtWidgets.QComboBox(self.groupBox)
        self.cmbComprobante.setGeometry(QtCore.QRect(135, 110, 120, 35))
        self.cmbComprobante.setStyleSheet("QComboBox {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QComboBox::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.cmbComprobante.setObjectName("cmbComprobante")
        self.cmbComprobante.addItem("")
        self.cmbComprobante.addItem("")
        self.cmbComprobante.addItem("")
        self.cmbProveedor = QtWidgets.QComboBox(self.groupBox)
        self.cmbProveedor.setGeometry(QtCore.QRect(375, 60, 221, 35))
        self.cmbProveedor.setStyleSheet("QComboBox {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QComboBox::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.cmbProveedor.setObjectName("cmbProveedor")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(285, 120, 67, 21))
        self.label_13.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.txtNumComprobante = QtWidgets.QLineEdit(self.groupBox)
        self.txtNumComprobante.setGeometry(QtCore.QRect(375, 110, 191, 35))
        self.txtNumComprobante.setStyleSheet("QLineEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtNumComprobante.setObjectName("txtNumComprobante")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(610, 70, 51, 21))
        self.label_14.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(15, 160, 891, 201))
        self.groupBox_2.setStyleSheet("/* Estilos para QGroupBox */\n"
"QGroupBox {\n"
"    border: 2px solid #1e362d;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    color: #1e362d;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    left: 10px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: none;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.txtFechaProd = QtWidgets.QDateEdit(self.groupBox_2)
        self.txtFechaProd.setGeometry(QtCore.QRect(580, 80, 120, 35))
        self.txtFechaProd.setAcceptDrops(False)
        self.txtFechaProd.setStyleSheet("/* Estilos para QDateEdit */\n"
"QDateEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QDateEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}")
        self.txtFechaProd.setAlignment(QtCore.Qt.AlignCenter)
        self.txtFechaProd.setCalendarPopup(True)
        self.txtFechaProd.setObjectName("txtFechaProd")
        self.txtFechaVenc = QtWidgets.QDateEdit(self.groupBox_2)
        self.txtFechaVenc.setGeometry(QtCore.QRect(580, 140, 120, 35))
        self.txtFechaVenc.setAcceptDrops(False)
        self.txtFechaVenc.setStyleSheet("/* Estilos para QDateEdit */\n"
"QDateEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QDateEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}")
        self.txtFechaVenc.setAlignment(QtCore.Qt.AlignCenter)
        self.txtFechaVenc.setCalendarPopup(True)
        self.txtFechaVenc.setObjectName("txtFechaVenc")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(480, 90, 101, 21))
        self.label_16.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(480, 150, 101, 21))
        self.label_17.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(480, 30, 121, 21))
        self.label_18.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(279, 90, 121, 21))
        self.label_19.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_19.setObjectName("label_19")
        self.txtPrecioCom = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtPrecioCom.setGeometry(QtCore.QRect(606, 20, 61, 35))
        self.txtPrecioCom.setStyleSheet("QLineEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtPrecioCom.setObjectName("txtPrecioCom")
        self.txtPrecioVen1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtPrecioVen1.setGeometry(QtCore.QRect(400, 80, 61, 35))
        self.txtPrecioVen1.setStyleSheet("QLineEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtPrecioVen1.setObjectName("txtPrecioVen1")
        self.cmbArticulo = QtWidgets.QComboBox(self.groupBox_2)
        self.cmbArticulo.setGeometry(QtCore.QRect(100, 80, 161, 35))
        self.cmbArticulo.setStyleSheet("QComboBox {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QComboBox::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.cmbArticulo.setObjectName("cmbArticulo")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_15.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.txtCantidad = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtCantidad.setGeometry(QtCore.QRect(100, 140, 61, 35))
        self.txtCantidad.setStyleSheet("QLineEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtCantidad.setObjectName("txtCantidad")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 150, 81, 21))
        self.label_20.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.txtCodArticulo = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtCodArticulo.setGeometry(QtCore.QRect(100, 20, 61, 30))
        self.txtCodArticulo.setStyleSheet("QLineEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtCodArticulo.setReadOnly(True)
        self.txtCodArticulo.setObjectName("txtCodArticulo")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(279, 30, 111, 21))
        self.label_22.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_22.setObjectName("label_22")
        self.txtPrecioVen = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtPrecioVen.setGeometry(QtCore.QRect(400, 20, 61, 35))
        self.txtPrecioVen.setStyleSheet("QLineEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtPrecioVen.setObjectName("txtPrecioVen")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(279, 150, 121, 21))
        self.label_23.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_23.setObjectName("label_23")
        self.txtPrecioVen2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtPrecioVen2.setGeometry(QtCore.QRect(400, 140, 61, 35))
        self.txtPrecioVen2.setStyleSheet("QLineEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtPrecioVen2.setObjectName("txtPrecioVen2")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(760, 90, 71, 21))
        self.label_24.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(770, 150, 51, 21))
        self.label_25.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_25.setObjectName("label_25")
        self.btnAgregar = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAgregar.setGeometry(QtCore.QRect(840, 80, 21, 37))
        self.btnAgregar.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c0dacb, stop: 1 #96bfab);\n"
"    color: #ffffff;\n"
"    border: 1px solid #1e362d;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #689f84, stop: 1 #96bfaa);\n"
"    border: 1px solid #96bfaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #2a5242, stop: 1 #32624d);\n"
"    border: 1px solid #32624d;\n"
"}")
        icon = QtGui.QIcon.fromTheme("audio-card")
        self.btnAgregar.setIcon(icon)
        self.btnAgregar.setObjectName("btnAgregar")
        self.btnQuitar = QtWidgets.QPushButton(self.groupBox_2)
        self.btnQuitar.setGeometry(QtCore.QRect(840, 140, 21, 37))
        self.btnQuitar.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #c0dacb, stop: 1 #96bfab);\n"
"    color: #ffffff;\n"
"    border: 1px solid #1e362d;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #689f84, stop: 1 #96bfaa);\n"
"    border: 1px solid #96bfaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #2a5242, stop: 1 #32624d);\n"
"    border: 1px solid #32624d;\n"
"}")
        icon = QtGui.QIcon.fromTheme("audio-card")
        self.btnQuitar.setIcon(icon)
        self.btnQuitar.setObjectName("btnQuitar")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.label_27.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_27.setObjectName("label_27")
        self.tbDetalleIngreso = QtWidgets.QTableView(self.groupBox)
        self.tbDetalleIngreso.setGeometry(QtCore.QRect(15, 380, 891, 221))
        self.tbDetalleIngreso.setStyleSheet("QTableView {\n"
"    background-color: #f2f7f4;\n"
"    border: 1px solid #cccccc;\n"
"    selection-background-color: #96bfaa;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QTableView QHeaderView {\n"
"    background-color: #c0dacb;\n"
"    color: #333333;\n"
"    border: none;\n"
"}\n"
"\n"
"QTableView QHeaderView::section {\n"
"    background-color: #deede3;\n"
"    color: #333333;\n"
"    padding: 6px;\n"
"    border: 1px solid #1e362d;\n"
"}\n"
"\n"
"QTableView QHeaderView::section:checked {\n"
"    background-color: #96bfaa;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #96bfaa;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QTableView::item:focus {\n"
"    background-color: #96bfaa;\n"
"    color: #ffffff;\n"
"    outline: none;\n"
"}")
        self.tbDetalleIngreso.setObjectName("tbDetalleIngreso")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(620, 120, 41, 21))
        self.label_21.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.txtItbis = QtWidgets.QLineEdit(self.groupBox)
        self.txtItbis.setGeometry(QtCore.QRect(670, 110, 120, 35))
        self.txtItbis.setStyleSheet("QLineEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtItbis.setText("")
        self.txtItbis.setObjectName("txtItbis")
        self.txtIdProveedor = QtWidgets.QLineEdit(self.groupBox)
        self.txtIdProveedor.setGeometry(QtCore.QRect(375, 20, 75, 30))
        self.txtIdProveedor.setStyleSheet("QLineEdit {\n"
"    background-color: #96bfab;\n"
"    border: 1px solid #cccccc;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #689f84;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #689f84;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #1e362d;\n"
"    font-weight: bold;\n"
"}")
        self.txtIdProveedor.setReadOnly(True)
        self.txtIdProveedor.setObjectName("txtIdProveedor")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(285, 30, 55, 21))
        self.label_4.setStyleSheet("QWidget {\n"
"    background-color: var(--jade-50);\n"
"}\n"
"\n"
"QLabel {\n"
"    color: var(--jade-500);\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.tbSesiones = QtWidgets.QTableView(self.centralwidget)
        self.tbSesiones.setGeometry(QtCore.QRect(790, 10, 51, 31))
        self.tbSesiones.setStyleSheet("")
        self.tbSesiones.setObjectName("tbSesiones")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ingresos almacen"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mantenimiento de los ingresos a almacen</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Nombre"))
        self.btnBuscar.setText(_translate("MainWindow", "Buscar"))
        self.btnBuscar.setShortcut(_translate("MainWindow", "Return"))
        self.btnAnular.setToolTip(_translate("MainWindow", "<html><head/><body><p>Anula el ingreso para que no se pueda vender posteriormente.</p></body></html>"))
        self.btnAnular.setText(_translate("MainWindow", "Anular"))
        self.btnImprimir.setText(_translate("MainWindow", "Imprimir"))
        self.label_10.setText(_translate("MainWindow", "Fecha Inicio"))
        self.label_11.setText(_translate("MainWindow", "Fecha Fin"))
        self.label_26.setText(_translate("MainWindow", "Estado"))
        self.cmbEstado.setToolTip(_translate("MainWindow", "<html><head/><body><p>Doble click para buscar articulos</p></body></html>"))
        self.cmbEstado.setItemText(0, _translate("MainWindow", "Activo"))
        self.cmbEstado.setItemText(1, _translate("MainWindow", "Inactivo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Listado"))
        self.label_3.setText(_translate("MainWindow", "Codigo"))
        self.btnRegistrar.setText(_translate("MainWindow", "Agregar"))
        self.txtCodigo.setToolTip(_translate("MainWindow", "Insertar codigo de articulo"))
        self.label_6.setText(_translate("MainWindow", "Comprobante"))
        self.label_12.setText(_translate("MainWindow", "Proveedor"))
        self.cmbComprobante.setItemText(0, _translate("MainWindow", "FACTURA"))
        self.cmbComprobante.setItemText(1, _translate("MainWindow", "RECIBO"))
        self.cmbComprobante.setItemText(2, _translate("MainWindow", "CONDUCE"))
        self.cmbProveedor.setToolTip(_translate("MainWindow", "<html><head/><body><p>Doble click para buscar proveedores</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Numero "))
        self.label_14.setText(_translate("MainWindow", "Fecha"))
        self.label_16.setText(_translate("MainWindow", "Fecha prod."))
        self.label_17.setText(_translate("MainWindow", "Fecha venc."))
        self.label_18.setText(_translate("MainWindow", "Precio compra"))
        self.label_19.setText(_translate("MainWindow", "Precio venta 2"))
        self.cmbArticulo.setToolTip(_translate("MainWindow", "<html><head/><body><p>Doble click para buscar articulos</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Articulo"))
        self.label_20.setText(_translate("MainWindow", "Cantidad"))
        self.label_22.setText(_translate("MainWindow", "Precio venta"))
        self.label_23.setText(_translate("MainWindow", "Precio venta 3"))
        self.label_24.setText(_translate("MainWindow", "Agregar "))
        self.label_25.setText(_translate("MainWindow", "Quitar"))
        self.btnAgregar.setText(_translate("MainWindow", "+"))
        self.btnQuitar.setText(_translate("MainWindow", "-"))
        self.label_27.setText(_translate("MainWindow", "Codigo"))
        self.label_21.setText(_translate("MainWindow", "Itbis"))
        self.label_4.setText(_translate("MainWindow", "Codigo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Mantenimiento"))
